name: List Files in Repo

on:
#  workflow_dispatch:      # Allows you to click a button to run this manually
#  push:
#    branches: [ master ]    # or trigger on push
  repository_dispatch:
    types: [jira-automated-modeling-ticket-status-change]

jobs:
  debug_files:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: echo "${{ github.event.client_payload }}"
#      # 1. Checkout the code (Crucial!)
#      - name: Checkout Code
#        uses: actions/checkout@v4

#      # 2. List all files recursively
#      - name: List all files
#        run: |
#          echo "Listing all files in the repository:"
#          ls -R